# persistentVolume for Stack
apiVersion: v1
kind: PersistentVolume
metadata:
  name: stt-stack
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/c/apps/STT-Playground/data"

---
# Create Persistence volume
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pvc
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce

---
# Start the mongodb server on k8s
apiVersion: v1
kind: Pod
metadata:
  name: registry
  labels:
    app.kubernetes.io/name: registry
spec:
  automountServiceAccountToken: false
  containers:
    - name: registry
      image: registry:2
      ports:
        - containerPort: 5000
          name: registry
      env:
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: "/certs/tls.crt"
        - name: REGISTRY_HTTP_TLS_KEY
          value: "/certs/tls.key"
      volumeMounts: 
        - name: registry-certs
          mountPath: "/certs"
          readOnly: true
        - name: registry-data
          mountPath: /var/lib/registry
      resources:
        limits:
          cpu: "2.0"
          memory: "1G"
          ephemeral-storage: "3G"
        requests:
          cpu: "0.1"
          memory: "10M"
          ephemeral-storage: "512M"
  volumes:
    - name: registry-certs
      secret:
        secretName: registry-cert 
    - name: registry-data
      persistentVolumeClaim: 
        claimName: registry-pvc

---
# Expose as services
apiVersion: v1
kind: Service
metadata:
  name: registry-service
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: registry
  ports:
    - name: registry-tcp
      protocol: TCP
      port: 5000
      targetPort: 5000
  loadBalancerIP: 10.211.55.250