# Start the mongodb server on k8s
apiVersion: v1
kind: Pod
metadata:
  name: mongo-stack
  labels:
    app.kubernetes.io/name: mongo
spec:
  automountServiceAccountToken: false
  volumes:
    - name: mongo-pv-store
      persistentVolumeClaim:
        claimName: mongo-pv-claim
  containers:
    - name: mongodb
      imagePullPolicy: Never
      image: test/mongodb
      ports:
        - containerPort: 27017
          name: datastore 
      volumeMounts:
        - mountPath: "/data/db/"
          name: mongo-pv-store
      resources:
        limits:
          cpu: "2.0"
          memory: "1G"
          ephemeral-storage: "3G"
        requests:
          cpu: "0.1"
          memory: "10M"
          ephemeral-storage: "512M"
---
# Expose as services
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app.kubernetes.io/name: mongo
  ports:
  - name: datastore-public
    protocol: TCP
    port: 27017
    targetPort: datastore
