# Deploy api to kubernetes
apiVersion: v1 
kind: Pod 
metadata:
  name: api-stack
  labels:
    app.kubernetes.io/name: stt-api
spec:
  automountServiceAccountToken: false
  containers:
    - name: stt-api
      imagePullPolicy: Never
      image: test/stt-api
      ports:
        - containerPort: 8080
          name: stt-api-port 
      volumeMounts: 
        - name: stt-api-conf
          mountPath: ./db.properties
          subPath: db.properties
          readOnly: true
        - name: stt-api-creds
          mountPath: ./creds.properties
          subPath: tokens
      resources:
        limits:
          cpu: "2.0"
          memory: "1G"
          ephemeral-storage: "3G"
        requests:
          cpu: "0.1"
          memory: "10M"
          ephemeral-storage: "512M"
  volumes:
    - name: stt-api-creds
      secret:
        secretName: stt-api-creds 
    - name: stt-api-conf
      configMap: 
        name: stt-api-conf