apiVersion: v1 
kind: Pod 
metadata:
  name: api-stack
  labels:
    app.kubernetes.io/name: stt-api
spec:
  automountServiceAccountToken: false
  containers:
    - name: stt-api
      imagePullPolicy: Never
      image: test/stt-api
      ports:
        - containerPort: 8080
          name: stt-api-port 
      resources:
        limits:
          cpu: "2.0"
          memory: "1G"
          ephemeral-storage: "3G"
        requests:
          cpu: "0.1"
          memory: "10M"
          ephemeral-storage: "512M"